version: '3.7'

services:
  ecr-proxy:
    image: myaser/ecr-proxy:1.3.0
    ports:
      - published: 80
        target: 80
      - published: 443
        target: 443
    healthcheck:
      test: wget http://localhost/ping -q -O - || exit 1
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 60s
    secrets:
      - source: ecr_config_file
        target: config
        mode: 600
    configs:
      - source: ecr_security_contorls
        target: /etc/nginx/security_controls
    environment:
      - AWS_CONFIG_FILE=/run/secrets/config
      - SECURITY_CONTROL_CONFIGS=/etc/nginx/security_controls
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 32M
secrets:
  ecr_config_file:
    file: ./aws_config

configs:
  ecr_security_contorls:
    file: ./security_controls