version: '3.7'

services:
  ecr-proxy:
    image: catalinpan/aws-ecr-proxy
    ports:
      - published: 80
        target: 80
      - published: 4430
        target: 443
    healthcheck:
      test: wget http://localhost/ping -q -O - || exit 1
      interval: 60s
      timeout: 5s
      retries: 2
      start_period: 60s
    secrets:
      - source: ecr_config_file
        target: config
        mode: 600
    environment:
      - AWS_CONFIG_FILE=/run/secrets/config
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.05'
          memory: 32M
secrets:
  ecr_config_file:
    file: ./aws_config
